<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <link rel='stylesheet prefetch' href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900'>
    <link rel='stylesheet prefetch' href='http://fonts.googleapis.com/css?family=Montserrat:400,700'>
    <link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic'
          rel='stylesheet' type='text/css'>
    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style-980.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')

        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');


    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/index.js')
        ->prependFile($this->basePath() . '/js/jquery.smartPlaceholder.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')

        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>
<body>

<div class="container">
    <?php echo $this->content; ?>

</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
<script type="text/javascript">
    $(function(){
        $(function() {
            $("input").smartPlaceholder(

                {
                    backgroundColor: '##f2f2f2',  // hex, rgb, rgba
                    color: '#000',            // hex, rgb, rgba
                    size: 12,                 // in pixels
                    speed: 0.8,               // in secs
                    radius: 3,                // in pixels
                    indent: 5,                // in pixels
                    position: 'top',       // 'top' or 'bottom'
                    mode: 'inline'            // 'inline' or 'extend'
                }
            );
        });
    })
</script>
</body>
</html>
