<?php
    // module/Album/view/album/album/index.phtml:

    $title = 'My user';
    $this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>

</p>

<table class="table">
    <tr>
        <th>User</th>
        <th>Name</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($users as $user) : ?>
        <tr>
         <?php var_dump($user);?>
        </tr>
    <?php endforeach; ?>
</table>