<div class="form wrapper-small">
    <?php
        if ($this->errorMessages){
            echo '<ul class="error">';
            foreach($this->errorMessages as $message)
            {
                echo '<li>'.$message.'</li>';
            }
            echo '</ul>';
        }
        if ($this->successMessage){
            echo '<ul class="success">';
            foreach($this->successMessage as $message)
            {
                echo '<li>'.$message.'</li>';
            }
            echo '</ul>';
        }
    ?>
    <div class="dashboard">
        <form method="POST" action="/patient/save" class="login-form">
            <input type="text" name="name" placeholder="name" data-validation="length" data-validation-length="min4" value="<?php echo $this->data['name'] ?>" required/>
            <input type="text" name="username" placeholder="username" data-validation="length" data-validation-length="min4" value="<?php echo $this->data['username'] ?>" required />
            <input type="password" name="password" placeholder="password" data-validation="length" data-validation-length="min4"  value="<?php echo $this->data['email'] ?>"required/>
            <input type="email" name="email" placeholder="email address" data-validation="email" value="<?php echo $this->data['name'] ?>" required/>
            <input type="date" name="dob" placeholder="date of birth" required value="<?php echo $this->data['dob'] ?>"/>
            <select id="gender" name="gender" class="form-control">
                <option value="M" <?php if($this->data['name']=='M'): ?>class="selected" <?php endif; ?>>Male</option>
                <option value="F" <?php if($this->data['name']=='F'): ?>class="selected" <?php endif; ?>>Female</option>
            </select>
            <input type="text" name="phone" placeholder="phone" data-validation="length" data-validation-length="min7" required value="<?php echo $this->data['phone'] ?>"/>
            <input type="text" name="address" placeholder="address" required value="<?php echo $this->data['address'] ?>"/>

            <button type="submit">create</button>

        </form>
    </div>
</div>