
<div class="form  wrapper-small">

    <?php
        if ($this->successMessage){
            echo '<ul class="success">';
            foreach($this->successMessage as $message)
            {
                echo '<li>'.$message.'</li>';
            }
            echo '</ul>';
        }
    ?>
    <div class="dashboard">
        <h1>Account Setting</h1>

        <form method="POST" action="/patient/doctorsave" class="login-form">
            <p class="field">Name</p>
            <input type="text" name="name" value="<?php echo $this->doctor['name'] ?>"placeholder="name" data-validation="length" data-validation-length="min4"/>

            <p class="field">Phone</p>
            <input type="phone" name="phone" value="<?php echo $this->doctor['phone'] ?>" ?>
            <p class="field">Email</p>
            <input type="email" name="email" value="<?php echo $this->doctor['email'] ?>" ?>
            <p class="field">Address</p>
            <input type="text" name="address" value="<?php echo $this->doctor['address'] ?>" ?>
            <button type="submit" name="update" value="update">Update</button>


        </form>
    </div>
</div>